import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SettingsProvider } from '@/contexts/SettingsContext';
import { UiSoundRuntime } from '@/components/UiSoundRuntime';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="/jsSID.js" defer></script>
      </head>
      <body className="antialiased">
        <SettingsProvider>
          <UiSoundRuntime />
          {children}
        </SettingsProvider>
      </body>
    </html>
  );
}
